// Code generated by protoc-gen-go.
// source: terraform-api.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	terraform-api.proto

It has these top-level messages:
	ApplyRequest
	ApplyResponse
	PlanRequest
	PlanResponse
	RefreshRequest
	RefreshResponse
	StateRequest
	StateResponse
	TaintRequest
	TaintResponse
	ValidateRequest
	ValidateResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ResourceState int32

const (
	ResourceState_StateUnknown      ResourceState = 0
	ResourceState_StateRunning      ResourceState = 1
	ResourceState_StateProvisioning ResourceState = 2
	ResourceState_StateSuccess      ResourceState = 3
	ResourceState_StateError        ResourceState = 4
)

var ResourceState_name = map[int32]string{
	0: "StateUnknown",
	1: "StateRunning",
	2: "StateProvisioning",
	3: "StateSuccess",
	4: "StateError",
}
var ResourceState_value = map[string]int32{
	"StateUnknown":      0,
	"StateRunning":      1,
	"StateProvisioning": 2,
	"StateSuccess":      3,
	"StateError":        4,
}

func (x ResourceState) String() string {
	return proto.EnumName(ResourceState_name, int32(x))
}
func (ResourceState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResourceAction int32

const (
	ResourceAction_ActionUnknown  ResourceAction = 0
	ResourceAction_ActionNone     ResourceAction = 1
	ResourceAction_ActionCreate   ResourceAction = 2
	ResourceAction_ActionUpdate   ResourceAction = 3
	ResourceAction_ActionDestroy  ResourceAction = 4
	ResourceAction_ActionRecreate ResourceAction = 5
)

var ResourceAction_name = map[int32]string{
	0: "ActionUnknown",
	1: "ActionNone",
	2: "ActionCreate",
	3: "ActionUpdate",
	4: "ActionDestroy",
	5: "ActionRecreate",
}
var ResourceAction_value = map[string]int32{
	"ActionUnknown":  0,
	"ActionNone":     1,
	"ActionCreate":   2,
	"ActionUpdate":   3,
	"ActionDestroy":  4,
	"ActionRecreate": 5,
}

func (x ResourceAction) String() string {
	return proto.EnumName(ResourceAction_name, int32(x))
}
func (ResourceAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ApplyRequest represents a apply request
type ApplyRequest struct {
	Config      []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Destroy     bool   `protobuf:"varint,2,opt,name=destroy" json:"destroy,omitempty"`
	Plan        []byte `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	Refresh     bool   `protobuf:"varint,4,opt,name=refresh" json:"refresh,omitempty"`
	State       []byte `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Parallelism int32  `protobuf:"varint,6,opt,name=parallelism" json:"parallelism,omitempty"`
}

func (m *ApplyRequest) Reset()                    { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()               {}
func (*ApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// ApplyResponse represents a apply response
type ApplyResponse struct {
	State  []byte                   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	States map[string]ResourceState `protobuf:"bytes,2,rep,name=states" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=pb.ResourceState"`
	Errors []string                 `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ApplyResponse) Reset()                    { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string            { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()               {}
func (*ApplyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApplyResponse) GetStates() map[string]ResourceState {
	if m != nil {
		return m.States
	}
	return nil
}

// PlanRequest represents a plan request
type PlanRequest struct {
	Config      []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Destroy     bool   `protobuf:"varint,2,opt,name=destroy" json:"destroy,omitempty"`
	Refresh     bool   `protobuf:"varint,3,opt,name=refresh" json:"refresh,omitempty"`
	State       []byte `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Parallelism int32  `protobuf:"varint,5,opt,name=parallelism" json:"parallelism,omitempty"`
}

func (m *PlanRequest) Reset()                    { *m = PlanRequest{} }
func (m *PlanRequest) String() string            { return proto.CompactTextString(m) }
func (*PlanRequest) ProtoMessage()               {}
func (*PlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// PlanResponse represents a plan response
type PlanResponse struct {
	Diff     []byte                    `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Actions  map[string]ResourceAction `protobuf:"bytes,2,rep,name=actions" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=pb.ResourceAction"`
	Plan     []byte                    `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	State    []byte                    `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Warnings []string                  `protobuf:"bytes,5,rep,name=warnings" json:"warnings,omitempty"`
}

func (m *PlanResponse) Reset()                    { *m = PlanResponse{} }
func (m *PlanResponse) String() string            { return proto.CompactTextString(m) }
func (*PlanResponse) ProtoMessage()               {}
func (*PlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlanResponse) GetActions() map[string]ResourceAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

// RefreshRequest represents a refresh request
type RefreshRequest struct {
	Config      []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	State       []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Parallelism int32  `protobuf:"varint,3,opt,name=parallelism" json:"parallelism,omitempty"`
}

func (m *RefreshRequest) Reset()                    { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string            { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()               {}
func (*RefreshRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// RefreshResponse represents a refresh response
type RefreshResponse struct {
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *RefreshResponse) Reset()                    { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string            { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()               {}
func (*RefreshResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// StateRequest represents a new state request
type StateRequest struct {
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// StateResponse represents a new state response
type StateResponse struct {
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// TaintRequest represents a taint request
type TaintRequest struct {
	Module   string `protobuf:"bytes,1,opt,name=module" json:"module,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	State    []byte `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *TaintRequest) Reset()                    { *m = TaintRequest{} }
func (m *TaintRequest) String() string            { return proto.CompactTextString(m) }
func (*TaintRequest) ProtoMessage()               {}
func (*TaintRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// TaintResponse represents a taint response
type TaintResponse struct {
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *TaintResponse) Reset()                    { *m = TaintResponse{} }
func (m *TaintResponse) String() string            { return proto.CompactTextString(m) }
func (*TaintResponse) ProtoMessage()               {}
func (*TaintResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// ValidateRequest represents a validation request
type ValidateRequest struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *ValidateRequest) Reset()                    { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string            { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()               {}
func (*ValidateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// ValidateResponse represents a validation response
type ValidateResponse struct {
	Valid    bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Warnings []string `protobuf:"bytes,2,rep,name=warnings" json:"warnings,omitempty"`
	Errors   []string `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ValidateResponse) Reset()                    { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()               {}
func (*ValidateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "pb.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "pb.ApplyResponse")
	proto.RegisterType((*PlanRequest)(nil), "pb.PlanRequest")
	proto.RegisterType((*PlanResponse)(nil), "pb.PlanResponse")
	proto.RegisterType((*RefreshRequest)(nil), "pb.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "pb.RefreshResponse")
	proto.RegisterType((*StateRequest)(nil), "pb.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "pb.StateResponse")
	proto.RegisterType((*TaintRequest)(nil), "pb.TaintRequest")
	proto.RegisterType((*TaintResponse)(nil), "pb.TaintResponse")
	proto.RegisterType((*ValidateRequest)(nil), "pb.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "pb.ValidateResponse")
	proto.RegisterEnum("pb.ResourceState", ResourceState_name, ResourceState_value)
	proto.RegisterEnum("pb.ResourceAction", ResourceAction_name, ResourceAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Terraform service

type TerraformClient interface {
	// Build or update the infrastructure
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (Terraform_ApplyClient, error)
	// Generate a diff and execution plan
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// Update the state against real resources
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Get a new empty state
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	// Mark a resource for recreation
	Taint(ctx context.Context, in *TaintRequest, opts ...grpc.CallOption) (*TaintResponse, error)
	// Validate a Terraform configuration
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type terraformClient struct {
	cc *grpc.ClientConn
}

func NewTerraformClient(cc *grpc.ClientConn) TerraformClient {
	return &terraformClient{cc}
}

func (c *terraformClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (Terraform_ApplyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Terraform_serviceDesc.Streams[0], c.cc, "/pb.Terraform/Apply", opts...)
	if err != nil {
		return nil, err
	}
	x := &terraformApplyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Terraform_ApplyClient interface {
	Recv() (*ApplyResponse, error)
	grpc.ClientStream
}

type terraformApplyClient struct {
	grpc.ClientStream
}

func (x *terraformApplyClient) Recv() (*ApplyResponse, error) {
	m := new(ApplyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *terraformClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := grpc.Invoke(ctx, "/pb.Terraform/Plan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := grpc.Invoke(ctx, "/pb.Terraform/Refresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/pb.Terraform/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Taint(ctx context.Context, in *TaintRequest, opts ...grpc.CallOption) (*TaintResponse, error) {
	out := new(TaintResponse)
	err := grpc.Invoke(ctx, "/pb.Terraform/Taint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/pb.Terraform/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Terraform service

type TerraformServer interface {
	// Build or update the infrastructure
	Apply(*ApplyRequest, Terraform_ApplyServer) error
	// Generate a diff and execution plan
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// Update the state against real resources
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Get a new empty state
	State(context.Context, *StateRequest) (*StateResponse, error)
	// Mark a resource for recreation
	Taint(context.Context, *TaintRequest) (*TaintResponse, error)
	// Validate a Terraform configuration
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterTerraformServer(s *grpc.Server, srv TerraformServer) {
	s.RegisterService(&_Terraform_serviceDesc, srv)
}

func _Terraform_Apply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApplyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TerraformServer).Apply(m, &terraformApplyServer{stream})
}

type Terraform_ApplyServer interface {
	Send(*ApplyResponse) error
	grpc.ServerStream
}

type terraformApplyServer struct {
	grpc.ServerStream
}

func (x *terraformApplyServer) Send(m *ApplyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Terraform_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TerraformServer).Plan(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Terraform_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TerraformServer).Refresh(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Terraform_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TerraformServer).State(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Terraform_Taint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TerraformServer).Taint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Terraform_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TerraformServer).Validate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Terraform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Terraform",
	HandlerType: (*TerraformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _Terraform_Plan_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Terraform_Refresh_Handler,
		},
		{
			MethodName: "State",
			Handler:    _Terraform_State_Handler,
		},
		{
			MethodName: "Taint",
			Handler:    _Terraform_Taint_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Terraform_Validate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Apply",
			Handler:       _Terraform_Apply_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xe3, 0x38, 0x4d, 0x26, 0x4e, 0xe2, 0x6c, 0x41, 0xb2, 0x22, 0x81, 0x5a, 0x9f, 0xaa,
	0xa2, 0x5a, 0x55, 0x41, 0x02, 0x71, 0x81, 0xd2, 0xf6, 0x8a, 0xaa, 0xb4, 0x70, 0x77, 0x9d, 0x4d,
	0xb1, 0xea, 0xee, 0x9a, 0x5d, 0xbb, 0x55, 0x2e, 0xbc, 0x0a, 0xcf, 0xc1, 0x89, 0x57, 0x63, 0xff,
	0x62, 0xaf, 0x43, 0x90, 0xb8, 0xd9, 0xf3, 0xf7, 0xcd, 0x7c, 0xf3, 0xcd, 0xc2, 0x5e, 0x89, 0x19,
	0x4b, 0x96, 0x94, 0x3d, 0x1c, 0x27, 0x45, 0x16, 0x17, 0x8c, 0x96, 0x14, 0x75, 0x8a, 0xdb, 0x88,
	0x81, 0x7f, 0x56, 0x14, 0xf9, 0x6a, 0x8e, 0xbf, 0x57, 0x98, 0x97, 0x68, 0x0c, 0xbd, 0x94, 0x92,
	0x65, 0x76, 0x17, 0x3a, 0xfb, 0xce, 0xa1, 0x8f, 0x26, 0xb0, 0xbb, 0x10, 0x76, 0x46, 0x57, 0x61,
	0x47, 0x18, 0xfa, 0xc8, 0x87, 0x6e, 0x91, 0x27, 0x24, 0x74, 0xd7, 0x6e, 0x86, 0x97, 0x0c, 0xf3,
	0x6f, 0x61, 0x57, 0xb9, 0x47, 0xe0, 0xf1, 0x32, 0x29, 0x71, 0xe8, 0x29, 0xff, 0x1e, 0x0c, 0x8b,
	0x84, 0x25, 0x79, 0x8e, 0xf3, 0x8c, 0x3f, 0x84, 0x3d, 0x61, 0xf4, 0xa2, 0x9f, 0x0e, 0x8c, 0x0c,
	0x28, 0x2f, 0x28, 0xe1, 0xb8, 0xc9, 0xd2, 0xa0, 0xc7, 0xd0, 0x53, 0xbf, 0x5c, 0x60, 0xba, 0x87,
	0xc3, 0xd3, 0x17, 0x71, 0x71, 0x1b, 0xb7, 0x32, 0xe2, 0x6b, 0xe5, 0xbf, 0x24, 0x25, 0x5b, 0xc9,
	0x9e, 0xc5, 0x74, 0x94, 0x71, 0xd1, 0x94, 0x7b, 0x38, 0x98, 0x7d, 0x84, 0xa1, 0xed, 0x1e, 0x82,
	0x7b, 0x8f, 0x57, 0xaa, 0xf4, 0x00, 0xed, 0x83, 0xf7, 0x98, 0xe4, 0x15, 0x56, 0xd3, 0x8c, 0x4f,
	0xa7, 0xb2, 0xb2, 0x28, 0x4a, 0x2b, 0x96, 0x62, 0x95, 0xf4, 0xbe, 0xf3, 0xce, 0x89, 0x52, 0x18,
	0x5e, 0x89, 0x21, 0xff, 0x9b, 0x14, 0x8b, 0x06, 0xb7, 0x4d, 0x43, 0x77, 0x1b, 0x0d, 0x9e, 0xa2,
	0xe1, 0xb7, 0x03, 0xbe, 0x46, 0x31, 0x2c, 0x08, 0x6a, 0x17, 0xd9, 0x72, 0x69, 0x40, 0x62, 0xd8,
	0x4d, 0xd2, 0x32, 0x13, 0x1e, 0x9b, 0x05, 0x3b, 0x21, 0x3e, 0xd3, 0x7e, 0x3d, 0x66, 0x7b, 0x31,
	0x1b, 0x0d, 0x04, 0xd0, 0x7f, 0x4a, 0x18, 0xc9, 0xc8, 0x1d, 0x17, 0xe8, 0x92, 0xa4, 0x4f, 0x62,
	0xf1, 0x76, 0x7a, 0x8b, 0xa5, 0x83, 0x36, 0x4b, 0xc8, 0x66, 0x49, 0x67, 0x29, 0x9a, 0x2e, 0x60,
	0x3c, 0xd7, 0x63, 0xff, 0x8b, 0xa9, 0xba, 0x8d, 0xce, 0x36, 0x1e, 0x5c, 0xc5, 0xc3, 0x3e, 0x4c,
	0xea, 0x2a, 0x5b, 0xf5, 0x10, 0x8d, 0xc1, 0x57, 0xbb, 0x31, 0x28, 0xd1, 0x4b, 0x18, 0x99, 0xff,
	0xed, 0xf1, 0x1f, 0xc0, 0xbf, 0x49, 0x32, 0x52, 0x5a, 0x5d, 0x3d, 0xd0, 0x45, 0x95, 0x63, 0x33,
	0x9e, 0x60, 0x83, 0x99, 0x69, 0x54, 0x63, 0x83, 0xa6, 0x80, 0x62, 0x4f, 0x02, 0x98, 0x02, 0xdb,
	0x01, 0x0e, 0x60, 0xf2, 0x35, 0xc9, 0xb3, 0x45, 0xd3, 0xd3, 0xe6, 0xe4, 0xd1, 0x39, 0x04, 0x4d,
	0x48, 0x53, 0xe5, 0x51, 0xda, 0x54, 0x48, 0xbf, 0xb5, 0x14, 0xb9, 0xe2, 0xc1, 0xa6, 0x92, 0x8f,
	0x72, 0x18, 0xb5, 0xc4, 0x29, 0x52, 0x34, 0x13, 0x5f, 0xc8, 0x3d, 0xa1, 0x4f, 0x24, 0xd8, 0xa9,
	0x2d, 0xf3, 0x8a, 0xc8, 0x4a, 0x81, 0x83, 0x9e, 0xc3, 0x54, 0x59, 0xae, 0x18, 0x7d, 0xcc, 0xb8,
	0xd8, 0x95, 0x34, 0x77, 0xea, 0xc0, 0xeb, 0x2a, 0x4d, 0x31, 0xe7, 0x81, 0x2b, 0xd0, 0x40, 0x59,
	0x2e, 0x25, 0x64, 0xd0, 0x3d, 0xfa, 0x21, 0xd7, 0x69, 0x2f, 0x19, 0x4d, 0xc5, 0xa1, 0xaa, 0xaf,
	0x06, 0x4f, 0x24, 0x69, 0xd3, 0x67, 0x4a, 0xb0, 0x40, 0x0b, 0xd6, 0x3a, 0x3a, 0x67, 0x58, 0xd4,
	0xd2, 0x40, 0x26, 0xa9, 0x90, 0xd3, 0x0b, 0xa0, 0xba, 0xcc, 0x85, 0xbe, 0x9a, 0xa0, 0x8b, 0x10,
	0x8c, 0xb5, 0x69, 0x8e, 0x53, 0x9d, 0xe8, 0x9d, 0xfe, 0xea, 0xc0, 0xe0, 0x66, 0xfd, 0x4e, 0xa1,
	0x13, 0xf0, 0xd4, 0xc9, 0xa3, 0xc0, 0xba, 0x7e, 0xc5, 0xf5, 0x6c, 0xfa, 0xd7, 0x7b, 0x10, 0xed,
	0x9c, 0x38, 0xe8, 0x15, 0x74, 0xe5, 0x79, 0xa0, 0x49, 0x73, 0x28, 0x3a, 0x3e, 0xd8, 0xbc, 0x9c,
	0x68, 0x07, 0xbd, 0x81, 0x5d, 0xa3, 0x3a, 0x64, 0xe4, 0x6d, 0x0b, 0x79, 0xb6, 0xd7, 0xb2, 0xd5,
	0x59, 0x31, 0x78, 0x66, 0x11, 0xd2, 0x6f, 0x8b, 0x52, 0x37, 0xd5, 0x92, 0xa5, 0x8e, 0x57, 0x42,
	0xd2, 0xf1, 0xb6, 0x28, 0x75, 0x7c, 0x4b, 0x65, 0x22, 0xfe, 0x2d, 0xf4, 0xd7, 0xaa, 0x41, 0xaa,
	0x85, 0x0d, 0x99, 0xcd, 0x9e, 0xb5, 0x8d, 0xeb, 0xc4, 0xdb, 0x9e, 0x7a, 0xd2, 0x5f, 0xff, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0x79, 0xc5, 0x60, 0xe9, 0x05, 0x00, 0x00,
}
